Repository remsfal/remsfal-backend, pull requests merged in 2024-11, with the labels that each got.

#248 Change Warning to Error and checkstyle correction
  remsfal-core/src/main/java/de/remsfal/core/api/AddressEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/ProjectEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/UserEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/project/ApartmentEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/project/BuildingEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/project/DefectEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/project/GarageEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/project/PropertyEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/project/SiteEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/project/TaskEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/json/ProjectListJson.java
  remsfal-core/src/main/java/de/remsfal/core/json/project/PropertyListJson.java
  remsfal-service/src/main/java/de/remsfal/service/boundary/ProjectResource.java
  remsfal-service/src/main/java/de/remsfal/service/boundary/project/SiteResource.java
  remsfal-service/src/main/java/de/remsfal/service/control/BuildingController.java
  remsfal-service/src/main/java/de/remsfal/service/control/ProjectController.java
  remsfal-service/src/main/java/de/remsfal/service/control/PropertyController.java
  remsfal-service/src/main/java/de/remsfal/service/control/SiteController.java
  remsfal-service/src/main/java/de/remsfal/service/control/TaskController.java
  remsfal-service/src/main/java/de/remsfal/service/entity/dto/AddressEntity.java
  remsfal-service/src/main/java/de/remsfal/service/entity/dto/AddressValidationEntity.java
  src/main/style/checkstyle.xml
Labels: good first issue

#245 New Tests for ProjectMembershipEntity
  remsfal-service/src/test/java/de/remsfal/service/entity/ProjectMembershipEntityTest.java
Labels: good first issue

#254 Write a HowTo import eclipse-js-formater.xml #193
  formatter/README.md
Labels: good first issue

#250 Fix:227 Fix NullPointer Exception on Getting Task Request with no OwnerID
  remsfal-core/src/main/java/de/remsfal/core/json/project/TaskItemJson.java
  remsfal-service/src/test/java/de/remsfal/service/boundary/project/TaskResourceTest.java
Labels: good first issue

#256 Cookie TTL Extentsion via ContainerResponseFilter ((#36)[https://github.com/remsfal/remsfal-backend/issues/36])
  remsfal-service/src/main/java/de/remsfal/service/boundary/authentication/HeaderExtensionResponseFilter.java
  remsfal-service/src/main/java/de/remsfal/service/boundary/authentication/SessionInfo.java
  remsfal-service/src/main/java/de/remsfal/service/boundary/authentication/SessionManager.java
  remsfal-service/src/test/java/de/remsfal/service/boundary/authentication/SessionInfoTest.java
  remsfal-service/src/test/java/de/remsfal/service/boundary/authentication/SessionManagerTest.java
Labels: good first issue

#249 Feature/add checkstyle rule trailing spaces
  remsfal-core/src/main/java/de/remsfal/core/api/AddressEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/project/ApartmentEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/project/GarageEndpoint.java
  remsfal-service/src/main/java/de/remsfal/service/boundary/BuildingResource.java
  remsfal-service/src/main/java/de/remsfal/service/boundary/authentication/SessionManager.java
  remsfal-service/src/main/java/de/remsfal/service/control/TaskController.java
  remsfal-service/src/main/java/de/remsfal/service/entity/dao/ProjectRepository.java
  src/main/style/checkstyle.xml
Labels: good first issue

#258 added event observer for testing
  .github/workflows/sonar-analysis.yml
  remsfal-core/pom.xml
  remsfal-core/src/test/java/de/remsfal/core/json/ProjectMemberListJsonTest.java
  remsfal-service/pom.xml
  remsfal-service/src/test/java/de/remsfal/service/boundary/AuthenticationEventObserver.java
  remsfal-service/src/test/java/de/remsfal/service/boundary/AuthenticationResourceMockitoTest.java
Labels: help wanted

#246 added maven wrapper files to root project
  .mvn/wrapper/.gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
Labels: good first issue

#239 Initial Implementation of Chat Functionality
  remsfal-core/pom.xml
  remsfal-core/src/main/java/de/remsfal/core/api/project/ChatEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/project/DefectEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/api/project/TaskEndpoint.java
  remsfal-core/src/main/java/de/remsfal/core/json/project/ChatMessageJson.java
  remsfal-core/src/main/java/de/remsfal/core/json/project/ChatMessageListJson.java
  remsfal-core/src/main/java/de/remsfal/core/json/project/ChatSessionJson.java
  remsfal-core/src/main/java/de/remsfal/core/model/project/ChatMessageModel.java
  remsfal-core/src/main/java/de/remsfal/core/model/project/ChatSessionModel.java
  remsfal-service/pom.xml
  remsfal-service/src/main/java/de/remsfal/service/boundary/project/ChatResource.java
  remsfal-service/src/main/java/de/remsfal/service/boundary/project/DefectResource.java
  remsfal-service/src/main/java/de/remsfal/service/boundary/project/TaskResource.java
  remsfal-service/src/main/java/de/remsfal/service/control/ChatMessageController.java
  remsfal-service/src/main/java/de/remsfal/service/control/ChatSessionController.java
  remsfal-service/src/main/java/de/remsfal/service/entity/dao/ChatMessageRepository.java
  remsfal-service/src/main/java/de/remsfal/service/entity/dao/ChatSessionRepository.java
  remsfal-service/src/main/java/de/remsfal/service/entity/dto/ChatMessageEntity.java
  remsfal-service/src/main/java/de/remsfal/service/entity/dto/ChatSessionEntity.java
  remsfal-service/src/main/resources/META-INF/liquibase-changelog-0_1_1.xml
  remsfal-service/src/main/resources/META-INF/liquibase-changelog.xml
  remsfal-service/src/test/java/de/remsfal/service/boundary/project/ChatResourceTest.java
  remsfal-service/src/test/java/de/remsfal/service/entity/ChatMessageRepositoryTest.java
  remsfal-service/src/test/java/de/remsfal/service/entity/ChatSessionRepositoryTest.java
Labels: thesis
